require "clockwork_mango"

module ClockworkMango
  module Holidays
    module InternationalObservance
      extend HolidayCollection

      GLOBAL_FAMILY_DAY                                              = Clockwork { january(1) } #  formerly One Day of Peace and Sharing, recognized by the UN
      WORLD_DAY_FOR_WAR_ORPHANS_                                     = Clockwork { january(6) } #  initiated by (S.O.S Enfants En Detresse - www.soseed.org by Stephen N. Kinuthia)
      INTERNATIONAL_DAY_FOR_PEACE_IN_KENYA                           = Clockwork { january(11) } #  January 11, 2008. Recent events in the country left Kenyans in fear of their future. The stalemate between the political leaders has created opportunity for destructive forces, and organized militia, which have risen to kill innocent people (more than 450 killed, thousands injured and over 250,000 displaced - initiated by (Kenya Welfare Foundation & Kenya Development Network and Consortium)
      INTERNATIONAL_HOLOCAUST_REMEMBRANCE_DAY                        = Clockwork { january(27) } #  recognized by the UN
      DATA_PROTECTION_DAY                                            = Clockwork { january(28) } #  recognized by the Council of Europe [1]
      WORLD_WETLANDS_DAY                                             = Clockwork { february(2) }
      WORLD_CANCER_DAY                                               = Clockwork { february(4) }
      INTERNATIONAL_TACKY_EMAIL_FORMATTING_DAY                       = Clockwork { february(4) }
      DARWIN_DAY                                                     = Clockwork { february(12) }
      VALENTINES_DAY                                                 = Clockwork { february(14) }
      WORLD_DAY_OF_SOCIAL_JUSTICE                                    = Clockwork { february(20) } #  recognized by the UN
      INTERNATIONAL_MOTHER_LANGUAGE_DAY                              = Clockwork { february(21) } #  recognized by the UN
      WORLD_DAY_OF_THE_FIGHT_AGAINST_SEXUAL_EXPLOITATION             = Clockwork { march(4) } #  ONG GIPF (site (French))
      UNITED_NATIONS_DAY_FOR_WOMENS_RIGHTS_AND_INTERNATIONAL_PEACE   = Clockwork { march(8) } #  recognized by the UN
      INTERNATIONAL_WOMENS_DAY                                       = Clockwork { march(8) } #  recognized by the UN
      WORLD_CONSUMER_RIGHTS_DAY                                      = Clockwork { march(15) }
      INTERNATIONAL_DAY_OF_THE_FRANCOPHONIE                          = Clockwork { march(20) } #  (site (French))
      WORLD_SLEEP_DAY                                                = Clockwork { march(21) }
      INTERNATIONAL_DAY_FOR_THE_ELIMINATION_OF_RACIAL_DISCRIMINATION = Clockwork { march(21) } #  recognized by the UN
      WORLD_DAY_FOR_WATER                                            = Clockwork { march(22) } #  recognized by the UN
      WORLD_METEOROLOGICAL_DAY                                       = Clockwork { march(23) } #  recognized by the UN
      WORLD_TUBERCULOSIS_DAY                                         = Clockwork { march(24) } #  recognized by the UN
      INTERNATIONAL_DAY_OF_REMEMBRANCE_OF_THE_VICTIMS_OF_SLAVERY_AND_THE_TRANSATLANTIC_SLAVE_TRADE = Clockwork { march(25) } #  recognized by the UN
      WORLD_THEATRE_DAY                                                  = Clockwork { march(27) }
      WORLD_WEAR_ODD_SOCKS_DAY                                           = Clockwork { march(27) }
      WORLD_AUTISM_AWARENESS_DAY                                         = Clockwork { april(2) } #  recognized by the UN
      INTERNATIONAL_DAY_FOR_MINE_AWARENESS_AND_ASSISTANCE_IN_MINE_ACTION = Clockwork { april(4) } #  recognized by the UN
      WORLD_HEALTH_DAY                                                   = Clockwork { april(7) } #  recognized by the UN
      INTERNATIONAL_DAY_OF_REFLECTION_ON_THE_GENOCIDE_IN_RWANDA          = Clockwork { april(7) } #  recognized by the UN
      EARTH_DAY                                                          = Clockwork { april(22) }
      WORLD_BOOK_AND_COPYRIGHT_DAY                                       = Clockwork { april(23) } #  recognized by the UN
      INTERNATIONAL_NOSE_PICKING_DAY                                     = Clockwork { april(23) }
      WORLD_MALARIA_DAY                                                  = Clockwork { april(25) } #  recognized by the WHO
      WORLD_INTELLECTUAL_PROPERTY_DAY                                    = Clockwork { april(26) } #  recognized by the UN
      INTERNATIONAL_WORKERS_MEMORIAL_DAY                                 = Clockwork { april(28) }
      WORLD_DANCE_DAY                                                    = Clockwork { april(29) }
      MAY_DAY_                                                           = Clockwork { may(1) }
      LABOUR_DAY                                                         = Clockwork { may(1) }
      WORLD_PRESS_FREEDOM_DAY                                            = Clockwork { may(3) } #  recognized by the UN
      INTERNATIONAL_FIREFIGHTERS_DAY                                     = Clockwork { may(4) }
      WORLD_RED_CROSS_RED_CRESCENT_DAY                                   = Clockwork { may(8) }
      TIME_OF_REMEMBRANCE_AND_RECONCILIATION_FOR_THOSE_WHO_LOST_THEIR_LIVES_DURING_THE_SECOND_WORLD_WAR = Clockwork { may(9) } #  recognized by the UN
      INTERNATIONAL_NURSES_DAY                                      = Clockwork { may(12) }
      INTERNATIONAL_DAY_OF_FAMILIES                                 = Clockwork { may(15) } #  recognized by the UN
      WORLD_TELECOMMUNICATION_DAY                                   = Clockwork { may(17) } #  recognized by the UN
      WORLD_DAY_FOR_CULTURAL_DIVERSITY_FOR_DIALOGUE_AND_DEVELOPMENT = Clockwork { may(21) } #  recognized by the UN
      INTERNATIONAL_DAY_FOR_BIOLOGICAL_DIVERSITY                    = Clockwork { may(22) } #  recognized by the UN
      INTERNATIONAL_DAY_OF_UNITED_NATIONS_PEACEKEEPERS              = Clockwork { may(29) } #  recognized by the UN
      WORLD_NO_TOBACCO_DAY                                          = Clockwork { may(31) } #  recognized by the UN
      INTERNATIONAL_CHILDRENS_DAY                                   = Clockwork { june(1) }
      INTERNATIONAL_DAY_OF_INNOCENT_CHILDREN_VICTIMS_OF_AGGRESSION  = Clockwork { june(4) } #  recognized by the UN
      WORLD_ENVIRONMENT_DAY                                         = Clockwork { june(5) } #  recognized by the UN
      WORLD_BRAIN_TUMOUR_DAY                                        = Clockwork { june(8) }
      WORLD_OCEAN_DAY                                               = Clockwork { june(8) }
      WORLD_DAY_AGAINST_CHILD_LABOUR                                = Clockwork { june(12) }
      WORLD_BLOOD_DONOR_DAY                                         = Clockwork { june(14) } #  recognized by the UN
      WORLD_DAY_TO_COMBAT_DESERTIFICATION_AND_DROUGHT               = Clockwork { june(17) } #  recognized by the UN
      INTERNATIONAL_PICNIC_DAY                                      = Clockwork { june(18) }
      WORLD_REFUGEE_DAY                                             = Clockwork { june(20) } #  recognized by the UN
      WORLD_MUSIC_DAY                                               = Clockwork { june(21) }
      UNITED_NATIONS_PUBLIC_SERVICE_DAY                             = Clockwork { june(23) } #  recognized by the UN
      INTERNATIONAL_DAY_AGAINST_DRUG_ABUSE_AND_ILLICIT_TRAFFICKING = Clockwork { june(26) } #  recognized by the UN
      INTERNATIONAL_DAY_IN_SUPPORT_OF_VICTIMS_OF_TORTURE = Clockwork { june(26) } #  recognized by the UN
      WORLD_POPULATION_DAY                               = Clockwork { july(11) } #  recognized by the UN
      INTERNATIONAL_DAY_OF_THE_WORLDS_INDIGENOUS_PEOPLE  = Clockwork { august(9) } #  recognized by the UN[3][4]
      INTERNATIONAL_YOUTH_DAY                            = Clockwork { august(12) } #  recognized by the UN
      LEFT_HANDERS_DAY                                   = Clockwork { august(13) }
      INTERNATIONAL_DAY_FOR_THE_REMEMBRANCE_OF_THE_SLAVE_TRADE_AND_ITS_ABOLITION = Clockwork { august(23) } #  recognized by the UN
      NAMIBIA_DAY                    = Clockwork { august(26) } #  recognized by the UN
      ACCORDING_TO_HOYLE_DAY         = Clockwork { august(29) }
      INTERNATIONAL_LITERACY_DAY     = Clockwork { september(8) } #  recognized by the UN
      WORLD_FIRST_AID_DAY            = Clockwork { september(11) }
      INTERNATIONAL_DAY_OF_DEMOCRACY = Clockwork { september(15) } #  recognized by the UN
      INTERNATIONAL_DAY_FOR_THE_PRESERVATION_OF_THE_OZONE_LAYER = Clockwork { september(16) } #  recognized by the UN
      INTERNATIONAL_TALK_LIKE_A_PIRATE_DAY = Clockwork { september(19) }
      INTERNATIONAL_DAY_OF_PEACE           = Clockwork { september(21) } #  recognized by the UN
      WORLD_ALZHEIMERS_DAY                 = Clockwork { september(21) }
      WORLD_CAR_FREE_DAYS                  = Clockwork { september(22) }
      INTERNATIONAL_GRAB_HAND_DAY_NOT_RECOGNISED_BY_UN = Clockwork { september(25) } #  but only those in the GIS Industry, and all associated IT Disciplines.
      EUROPEAN_DAY_OF_LANGUAGES             = Clockwork { september(26) }
      WORLD_TOURISM_DAY                     = Clockwork { september(27) }
      RIGHT_TO_KNOW_DAY_                    = Clockwork { september(28) }
      WORLD_RABIES_DAY                      = Clockwork { september(28) }
      INTERNATIONAL_DAY_OF_OLDER_PERSONS    = Clockwork { october(1) } #  recognized by the UN
      WORLD_VEGETARIAN_DAY                  = Clockwork { october(1) }
      INTERNATIONAL_DAY_OF_NONVIOLENCE      = Clockwork { october(2) } #  recognized by the UN, observed on M.K. Gandhi's birthday
      WORLD_ANIMAL_DAY                      = Clockwork { october(4) }
      WORLD_TEACHERS_DAY                    = Clockwork { october(5) }
      WORLD_HOSPICE_AND_PALLIATIVE_CARE_DAY = Clockwork { october(6) }
      WORLD_HUMANITARIAN_ACTION_DAY         = Clockwork { october(8) }
      WORLD_POST_DAY                        = Clockwork { october(9) } #  recognized by the UN
      WORLD_MENTAL_HEALTH_DAY               = Clockwork { october(10) } #  recognized by the UN
      WORLD_DAY_AGAINST_DEATH_PENALTY       = Clockwork { october(10) } #  recognized by the WCADP
      WORLD_STANDARDS_DAY                   = Clockwork { october(14) }
      INTERNATIONAL_DAY_OF_RURAL_WOMEN      = Clockwork { october(15) } #  recognized by the UN
      FOUNDATION_OF_THE_BLACK_PANTHERS_DAY  = Clockwork { october(15) }
      WORLD_FOOD_DAY                        = Clockwork { october(16) } #  recognized by the UN
      INTERNATIONAL_DAY_FOR_THE_ERADICATION_OF_POVERTY = Clockwork { october(17) } #  recognized by the UN
      UNITED_NATIONS_DAY                               = Clockwork { october(24) } #  recognized by the UN
      WORLD_DEVELOPMENT_INFORMATION_DAY                = Clockwork { october(24) } #  recognized by the UN
      WORLD_VEGAN_DAY                                  = Clockwork { november(1) }
      INTERNATIONAL_DAY_FOR_PREVENTING_THE_EXPLOITATION_OF_THE_ENVIRONMENT_IN_WAR_AND_ARMED_CONFLICT = Clockwork { november(6) } #  recognized by the UN
      WORLD_FREEDOM_DAY               = Clockwork { november(9) }
      WORLD_DIABETES_DAY              = Clockwork { november(14) } #  recognized by the UN
      INTERNATIONAL_DAY_FOR_TOLERANCE = Clockwork { november(16) } #  recognized by the UN
      INTERNATIONAL_STUDENTS_DAY      = Clockwork { november(17) }
      WORLD_TOILET_DAY                = Clockwork { november(19) }
      AFRICA_INDUSTRIALIZATION_DAY    = Clockwork { november(20) } #  recognized by the UN
      UNIVERSAL_CHILDRENS_DAY         = Clockwork { november(20) } #  recognized by the UN
      WORLD_HELLO_DAY                 = Clockwork { november(21) }
      WORLD_TELEVISION_DAY            = Clockwork { november(21) } #  recognized by the UN
      INTERNATIONAL_DAY_FOR_THE_ELIMINATION_OF_VIOLENCE_AGAINST_WOMEN = Clockwork { november(25) } #  recognized by the UN
      INTERNATIONAL_DAY_OF_SOLIDARITY_WITH_THE_PALESTINIAN_PEOPLE     = Clockwork { november(29) } #  recognized by the UN
      WORLD_AIDS_DAY                                                  = Clockwork { december(1) } #  recognized by the UN
      ROMANIA_NATIONAL_DAY                                            = Clockwork { december(1) }
      INTERNATIONAL_DAY_FOR_THE_ABOLITION_OF_SLAVERY                  = Clockwork { december(2) } #  recognized by the UN
      INTERNATIONAL_DAY_OF_DISABLED_PERSONS                           = Clockwork { december(3) } #  recognized by the UN
      INTERNATIONAL_VOLUNTEER_DAY_FOR_ECONOMIC_AND_SOCIAL_DEVELOPMENT = Clockwork { december(5) } #  recognized by the UN
      INTERNATIONAL_CIVIL_AVIATION_DAY              = Clockwork { december(7) } #  recognized by the UN
      THE_INTERNATIONAL_DAY_AGAINST_CORRUPTION      = Clockwork { december(9) } #  recognized by the UN
      HUMAN_RIGHTS_DAY                              = Clockwork { december(10) } #  recognized by the UN
      INTERNATIONAL_MOUNTAIN_DAY                    = Clockwork { december(11) } #  recognized by the UN
      INTERNATIONAL_MIGRANTS_DAY                    = Clockwork { december(18) } #  recognized by the UN
      UNITED_NATIONS_DAY_FOR_SOUTHSOUTH_COOPERATION = Clockwork { december(19) } #  recognized by the UN
      INTERNATIONAL_HUMAN_SOLIDARITY_DAY            = Clockwork { december(20) } #  recognized by the UN


      INTERNATIONAL_PEACE_WEEK                          = Clockwork { september & mweek(4) } #* 4th week of September -
      WORLD_MARITIME_DAY                                = Clockwork { september & mweek(-1) } #* During last week of September - , recognized by the UN
      WORLD_HABITAT_DAY                                 = Clockwork { october & monday(1) }#* First Monday of October - , recognized by the UN
      WORLD_DAY_OF_REMEMBRANCE_FOR_ROAD_TRAFFIC_VICTIMS = Clockwork { november & sunday(3) } #* Third Sunday of November - , recognized by the UN
      INTERNATIONAL_DAY_FOR_NATURAL_DISASTER_REDUCTION  = Clockwork { october & wednesday(2) } #* Second Wednesday of October - , recognized by the UN
      INTERNATIONAL_DAY_OF_COOPERATIVES                 = Clockwork { july & saturday(1) } #* 1st Saturday of July - , recognized by the UN
      WORLD_ASTHMA_DAY                                  = Clockwork { may & tuesday(1) } #* 1st Tuesday of May -
      WORLD_FAIR_TRADE_DAY                              = Clockwork { may & saturday(2) } #* 2nd Saturday of May -

    end
  end
end
